[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "aoc"
version = "2023"
dependencies = []

[project.optional-dependencies]
dev = [
    "ruff",
    "pytest"
]


